Add: initial boilerplate and initial sz.rs (token and line counter
teeny-kth/teenygrad pull request #1
Opened 2024-04-20 19:17 UTC by 21st-centuryman

Hello Jay, @Jakunot
I implemented sz.rs in a test directory as well as moved all files around from src to src/teenygrad. 

I found the file structure in teenygrad to be annoying to deal with in rust.

We will need to implement sz.rs in github ci/cd. I think that could be something for you if youre ever bored and wanna do something on this project before we officially start in summer. I think this issue also is a great practice for both us of to understand how we request changes, 

I have some small stuff here that I dont think we should add, i leave it up to you to ask me to make changes to this PR.

Cherrio

2024-04-21 15:05 UTC, 21st-centuryman commented
#2

2024-04-21 15:07 UTC, 21st-centuryman commented
#3 
Still missing a feature which is listing it by folder
so all tinygrad in one, all nn in one etc.

2024-04-25 17:38 UTC, Jakunot commented on Cargo.toml
> +itertools = "0.12.1"
Remove this, not need/ not utilized

2024-04-25 17:40 UTC, Jakunot requested changes
Test

2024-04-25 17:41 UTC, Jakunot commented on Cargo.toml
> +itertools = "0.12.1"
Remove

2024-04-25 17:48 UTC, Jakunot commented on LICENSE
Revert back

2024-04-25 18:04 UTC, Jakunot requested changes
Fix suggested changes

2024-04-25 18:05 UTC, 21st-centuryman commented on src/tests/sz.rs
> +    let _headers = vec!["Name", "Lines", "Tokens/Line"];
[065a5e6](https://github.com/teeny-kth/teenygrad/pull/1/commits/065a5e6873a896d8a12576812ed5cba17ad4fb55)

2024-04-25 18:06 UTC, 21st-centuryman commented on src/teenygrad/tensor.rs
[065a5e6](https://github.com/teeny-kth/teenygrad/pull/1/commits/065a5e6873a896d8a12576812ed5cba17ad4fb55)

2024-04-25 18:06 UTC, 21st-centuryman commented on src/teenygrad/lazy.rs
[065a5e6](https://github.com/teeny-kth/teenygrad/pull/1/commits/065a5e6873a896d8a12576812ed5cba17ad4fb55)

2024-04-25 18:06 UTC, 21st-centuryman commented on src/teenygrad/function.rs
[065a5e6](https://github.com/teeny-kth/teenygrad/pull/1/commits/065a5e6873a896d8a12576812ed5cba17ad4fb55)

2024-04-25 18:06 UTC, 21st-centuryman commented on LICENSE
[065a5e6](https://github.com/teeny-kth/teenygrad/pull/1/commits/065a5e6873a896d8a12576812ed5cba17ad4fb55)

2024-04-25 18:07 UTC, 21st-centuryman commented on src/teenygrad/ops.rs
[fc8f1f8](https://github.com/teeny-kth/teenygrad/pull/1/commits/fc8f1f8602d18d9b4a25e67a5e1a18745a218c5b)

2024-04-25 18:07 UTC, 21st-centuryman commented on Cargo.toml
> +itertools = "0.12.1"
[fc8f1f8](https://github.com/teeny-kth/teenygrad/pull/1/commits/fc8f1f8602d18d9b4a25e67a5e1a18745a218c5b)

2024-04-25 18:09 UTC, Jakunot approved these changes
lgtm

2024-04-25 18:10 UTC, merged